wifi:
  networks:
    - ssid: !secret wifi_ssid_iot
      password: !secret wifi_password_iot
  
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $ssid